### ISSUE TITLE
Can't publish new version

### ISSUE THREAD

**Issue by SachaG** [meteor-utilities/avatar#37]
I'm trying to publish a new version for Meteor 1.2 compatibility, but I get the following error:

```
Sachas-MacBook-Pro:meteor-avatar sacha$ meteor publish
=> Errors while initializing project:

While building package utilities:avatar:
packages/check/match.js:299:1: Match error: Unknown key in field react (compiling react/avatar.jsx)
at packages/check/match.js:299:1
at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
at checkSubtree (packages/check/match.js:290:1)
at check (packages/check/match.js:32:1)
at Object.getDefaultOptions (packages/babel-compiler/babel.js:8:1)
at handler (packages/transpileJSX/jsx-plugin.js:4:1)
```

**Comment by SachaG** [comment]
Whoops never mind, somehow I hadn't pulled in all the latest changes.
