### ISSUE TITLE
Fail to build [react]

### ISSUE THREAD

**Issue by monocursive** [meteor-utilities/avatar#9]
Hi there.

When I run meteor I get this error:

```
W20150723-16:40:06.549(2)? (STDERR)
W20150723-16:40:06.551(2)? (STDERR) /Users/maz-dev/.meteor/packages/meteor-tool/.1.1.3.e9jr4p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150723-16:40:06.551(2)? (STDERR)                         throw(ex);
W20150723-16:40:06.551(2)? (STDERR)                               ^
W20150723-16:40:06.551(2)? (STDERR) ReferenceError: ReactMeteorData is not defined
W20150723-16:40:06.551(2)? (STDERR)     at packages/utilities:avatar/react/avatar.jsx:10:16
W20150723-16:40:06.551(2)? (STDERR)     at packages/utilities:avatar/react/avatar.jsx:81:7
W20150723-16:40:06.551(2)? (STDERR)     at /Users/maz-dev/code/dev/js/ramble/.meteor/local/build/programs/server/packages/utilities_avatar.js:512:3
W20150723-16:40:06.552(2)? (STDERR)     at /Users/maz-dev/code/dev/js/ramble/.meteor/local/build/programs/server/boot.js:222:10
W20150723-16:40:06.552(2)? (STDERR)     at Array.forEach (native)
W20150723-16:40:06.552(2)? (STDERR)     at Function._.each._.forEach (/Users/maz-dev/.meteor/packages/meteor-tool/.1.1.3.e9jr4p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150723-16:40:06.552(2)? (STDERR)     at /Users/maz-dev/code/dev/js/ramble/.meteor/local/build/programs/server/boot.js:117:5

```

The react package is indeed included.

Any idea on what might be the issue?

Thanks.

**Comment by timothyarmes** [comment]
You need have installed the official react package in your product. See here:

http://react-packages.readthedocs.org/en/latest/

That package will install the ReactMeteorData mixin.

Tim

**Comment by monocursive** [comment]
It's installed. I call the mixin without any problem clientside, the issue seems to be during the build phase serverside.

**Comment by timothyarmes** [comment]
At what point do you get the error, when you do `meteor run`?

**Comment by monocursive** [comment]
I have absolutely no idea what the problem was, but without changing anything to my code, everything is working now.

I just deleted and added the package again. 

Thanks for the package!
